### ISSUE TITLE
mseed format io

### ISSUE THREAD

**Issue by chauvetige** [xdas-dev/xdas#14]
Hello
I am new on the seismic processing and I am still looking at the option to process my data. As I am also going to use optic fiber I was thinking to do everything (seismic node + fiber) through xdas. You write in you github page that xdas can also be used for large seismic array.

My question is : is it possible to open mseed format ? Or will it be difficult to implement this.

Best
Thomas

**Comment by atrabattoni** [comment]
Hello
This statement about large seismic array was precisely meant to start a discussion about it :). There is still some work to do in that direction. 

Xdas already provide a way to convert obspy.Streams to xdas objects. What you can do right now:
1) open some mseed with obspy into a stream `st`.
2) convert it to an xdas DataArray with 
```python
import xdas as xd
da = xd.DataArray.from_stream(st)
```
But for now this suppose that all the trace in the stream 'st' are synchronized which can be a bit limiting. This code was initially meant for people that converts DAS data to traces so they can apply their traditional seismic processing routines. 

What would you like to acheive? Is your node dataset very big?

Best
Alister

**Comment by chauvetige** [comment]
OK perfect. I can start to try with this. For now I am only trying to do basic processing as spectrograms. I Couldn't do it using obspy my data set was to large or my option to demanding. Regarding my dataset for now I have one mount of data that is 10 Gb per node and 8 nodes. I am planning to have one year of data at the end.

I am new in all this but I have seen your web seminar in may. By the way, I am working on glacier with Florent Gimbert if you know him.

Best
Thomas

**Comment by atrabattoni** [comment]
Very interesting. I think for exploring your dataset in the short term obspy is better. In the long run, if you need to do a massive systematic analysis, Xdas might help you. Anyway, please get back to us if you need anything (I think spectrograms are not included in Xdas right now. I need to add that. I have most of them almost done). And yes, I know Florent very well.

**Comment by atrabattoni** [comment]
I found some time to add support for miniseed using dask as backend for virtualization. Yet probably a lot of feature will be missing to correctly handle seismic array datasets. For me the bigger concern is related to data synchronization and how to deal with gaps on only some stations. Because otherwise, everything can be put into N-dimensional arrays and everything works out of the box. 

Feedback is welcome. 

You can install this with:

`pip install git+https://github.com/xdas-dev/xdas.git@v0.2`

Related documentation is there:

https://xdas.readthedocs.io/en/v0.2/user-guide/miniseed.html

**Comment by atrabattoni** [comment]
I merge it into version 0.2. I will close that issue, please reopen other issues is you further need something.
